name = "Supervisors"
uuid = "60416940-50f5-4498-a9b5-9ed9995412c5"
authors = ["Paul Bayer"]
version = "0.1.0"

[compat]
julia = "1.5"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
